from agent.system_prompt.prompts import (
    SYSTEM_PROMPT_ROUTER,
    SYSTEM_PROMPT_MODERATION,
    SYSTEM_PROMPT_CLASSIFICATION,
    SYSTEM_PROMPT_CRITIC,
    SYSTEM_PROMPT_RESEARCHER,
    SYSTEM_PROMPT_CROSS_EVALUATION,
)
